variable "Name" {}
variable "Owner" {}
variable "Cost" {}
variable "Department" {}
variable "Division" {}
variable "Environment" {}
variable "Terraform" {}
variable "Use" {}
variable "Ansible" {}
variable "Internal" {}
variable "BackUps" {}
variable "PatchGroup" {}
