locals {
  # Absolute path to the bundled scripts (resolved at terraform init time).
  scripts_dir  = "${path.module}/files"
  wrapper      = "${local.scripts_dir}/all-unmanaged-resources.sh"
  check_script = "${local.scripts_dir}/check-unmanaged-resources.sh"
  scan_script  = "${local.scripts_dir}/scan-unmanaged-resources.sh"

  # Build the argument list passed to the wrapper.
  mode_flag = var.mode == "check-only" ? "--check-only" : (
    var.mode == "scan-only" ? "--scan-only" : ""
  )

  # Anchor auto-discovery to the CONSUMER's root module unless explicitly
  # overridden. Using path.root (the root module dir) is far more
  # deterministic than path.cwd (the dir terraform happened to be invoked
  # from) and prevents the scanner from latching onto a sibling repo's
  # ./aws folder by accident.
  effective_tf_dir = var.terraform_dir == "" ? path.root : var.terraform_dir
  effective_cwd    = var.working_dir == "" ? path.root : var.working_dir

  profile_args          = var.profile == "" ? [] : ["--profile", var.profile]
  region_args           = flatten([for r in var.regions : ["--region", r]])
  dir_args              = ["--dir", local.effective_tf_dir]
  json_args             = var.json_output ? ["--json"] : []
  mode_args             = local.mode_flag == "" ? [] : [local.mode_flag]
  expected_account_args = var.aws_account_id == "" ? [] : ["--expected-account", var.aws_account_id]
  repo_args             = var.repo_name == "" ? [] : ["--repo", var.repo_name]
  strict_args           = var.strict_profile ? ["--strict-profile"] : []

  invocation_args = concat(
    local.mode_args,
    local.profile_args,
    local.region_args,
    local.dir_args,
    local.json_args,
    local.expected_account_args,
    local.repo_args,
    local.strict_args,
  )

  # Shell-safe joined args (used by null_resource and outputs).
  invocation_args_str = join(" ", local.invocation_args)

  # README installation
  readme_source_path = "${path.module}/README.md"
  readme_dest_path = (
    var.readme_destination != ""
    ? var.readme_destination
    : "${path.root}/UNMANAGED_RESOURCES_SCANNER.md"
  )
  readme_banner = <<-EOT
    <!--
      This file is auto-generated by the `unmanaged-resources-scanner`
      Terraform module. It is a verbatim copy of the module's README.md
      and exists so the docs are available in this repo without needing
      to navigate to the modules repo.

      DO NOT EDIT BY HAND - changes will be overwritten on the next
      `terraform apply`. Update the README in the modules repo instead.

      To stop this file being generated, set `install_readme = false`
      on the module call.
    -->

  EOT

  # Whole-module copy
  module_copy_dest = (
    var.module_copy_destination != ""
    ? var.module_copy_destination
    : "${path.root}/.unmanaged-resources-scanner-module"
  )

  # All files in the module, minus the excluded patterns. fileset() returns
  # paths relative to path.module, which is exactly what we want for
  # rebuilding the directory tree on the destination side.
  module_all_files = var.install_module_copy ? fileset(path.module, "**") : toset([])
  module_excluded_files = var.install_module_copy ? toset(flatten([
    for pat in var.module_copy_exclude : tolist(fileset(path.module, pat))
  ])) : toset([])
  module_copy_files = setsubtract(local.module_all_files, local.module_excluded_files)
}

# Ensure shipped scripts are executable on the consumer machine after
# `terraform init` copies the module to .terraform/modules/<name>/files/.
# (We chmod every plan to be safe; cost is negligible.)
resource "null_resource" "ensure_executable" {
  triggers = {
    wrapper_hash = filesha256(local.wrapper)
    check_hash   = filesha256(local.check_script)
    scan_hash    = filesha256(local.scan_script)
  }

  provisioner "local-exec" {
    command     = "chmod +x '${local.wrapper}' '${local.check_script}' '${local.scan_script}'"
    interpreter = ["bash", "-c"]
  }
}

# Optional: run the scanner during `terraform apply`.
resource "null_resource" "run" {
  count = var.run_on_apply ? 1 : 0

  triggers = var.triggers

  provisioner "local-exec" {
    working_dir = local.effective_cwd
    command     = "'${local.wrapper}' ${local.invocation_args_str}"
    interpreter = ["bash", "-c"]

    environment = {
      SLACK_ENABLED     = var.slack_enabled ? "1" : "0"
      SLACK_WEBHOOK_URL = var.slack_webhook_url
      ACCOUNT_ID        = var.account_id
      EXPECTED_ACCOUNT  = var.aws_account_id
      REPO_NAME         = var.repo_name
      SETUP_SCRIPT      = var.setup_script
      STRICT_PROFILE    = var.strict_profile ? "1" : "0"
    }
  }

  depends_on = [null_resource.ensure_executable]
}

# Drop a copy of the module README into the consumer stack so users have
# the docs locally and don't need to jump back to the modules repo.
resource "local_file" "readme" {
  count = var.install_readme ? 1 : 0

  filename        = local.readme_dest_path
  content         = "${local.readme_banner}${file(local.readme_source_path)}"
  file_permission = "0644"
}

# Mirror the entire module directory (Terraform source, scripts, README,
# etc.) into the consumer's stack when install_module_copy = true. Each
# file is tracked as its own local_file resource so additions, deletions
# and edits are all picked up by `terraform apply` / `terraform destroy`.
#
# Files under files/ are written with 0755 so the shell scripts remain
# executable; everything else is 0644.
resource "local_file" "module_copy" {
  for_each = local.module_copy_files

  filename       = "${local.module_copy_dest}/${each.value}"
  content_base64 = filebase64("${path.module}/${each.value}")
  file_permission = (
    startswith(each.value, "files/") || endswith(each.value, ".sh")
    ? "0755"
    : "0644"
  )
  directory_permission = "0755"
}

# Drop a small NOTICE at the root of the module copy so anyone browsing it
# knows it is auto-generated.
resource "local_file" "module_copy_notice" {
  count = var.install_module_copy ? 1 : 0

  filename        = "${local.module_copy_dest}/AUTO_GENERATED.md"
  file_permission = "0644"
  content         = <<-EOT
    # Auto-generated module copy

    This directory is a verbatim copy of the `unmanaged-resources-scanner`
    Terraform module, written here by Terraform on every `terraform apply`.

    **Do not edit these files by hand** - your changes will be silently
    overwritten on the next apply. Update the canonical module in the
    modules repo and re-apply.

    To stop this directory being generated, set `install_module_copy = false`
    on the module call. To remove it, run `terraform destroy` (or just delete
    the local_file resources from state).
  EOT
}
