from . import cloudwatch, ec2, ecs, elb, iam, kms, lambda_fn, rds, route53, s3, dynamodb, sns, sqs, vpc

REGISTRY = {
    "EC2 Instance": ec2.instances,
    "EBS Volume": ec2.volumes,
    "EBS Snapshot": ec2.snapshots,
    "AMI": ec2.amis,
    "Elastic IP": ec2.elastic_ips,
    "Key Pair": ec2.key_pairs,
    "Security Group": vpc.security_groups,
    "ENI": vpc.enis,
    "NAT Gateway": vpc.nat_gateways,
    "Internet Gateway": vpc.internet_gateways,
    "VPC": vpc.vpcs,
    "Subnet": vpc.subnets,
    "Route Table": vpc.route_tables,
    "Network ACL": vpc.network_acls,
    "VPC Endpoint": vpc.vpc_endpoints,
    "IAM Role": iam.roles,
    "IAM User": iam.users,
    "IAM Group": iam.groups,
    "IAM Policy": iam.policies,
    "CloudTrail": iam.cloudtrails,
    "S3 Bucket": s3.buckets,
    "Lambda": lambda_fn.functions,
    "RDS": rds.instances,
    "RDS Snapshot": rds.snapshots,
    "ECS Cluster": ecs.clusters,
    "ECS Service": ecs.services,
    "KMS Key": kms.keys,
    "Load Balancer": elb.load_balancers,
    "Classic LB": elb.classic_load_balancers,
    "Target Group": elb.target_groups,
    "Route53 Hosted Zone": route53.hosted_zones,
    "DynamoDB Table": dynamodb.tables,
    "SNS Topic": sns.topics,
    "SQS Queue": sqs.queues,
    "Log Group": cloudwatch.log_groups,
    "SSM Param": cloudwatch.ssm_parameters,
    "Schedule": cloudwatch.schedules,
    "Secret": cloudwatch.secrets,
    "ECR Repo": ecs.ecr_repositories,
}

for scanner in [iam.roles, iam.users, iam.groups, iam.policies, iam.cloudtrails, s3.buckets, route53.hosted_zones]:
    scanner.global_only = True
